# Generated by Django 4.1.2 on 2022-10-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(db_index=True, max_length=30)),
                ('lname', models.CharField(db_index=True, max_length=30)),
                ('personal_phone', models.CharField(db_index=True, max_length=30)),
                ('work_phone', models.CharField(db_index=True, max_length=30)),
                ('address', models.CharField(db_index=True, max_length=30)),
            ],
        ),
    ]
