# Generated by Django 4.1.2 on 2022-10-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('lname',), 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
    ]
